# Default configurations

name : Phi
source : articles
destination : site
assets : assets
templates : templates
timezone: America/New_York
exclude_name :
exclude_path : 
defaults:
	# match againt what ?
	- pattern : *
	  meta : 
	  	# :structure, :title, :year, :short_year, :month, :short_month, :day, :short_day 
	  	# :date (filename must in year-mon-day-title format)
	  	# a better configuration class
	  	title : :name
	  	url : :date/:name.html
	  	template : article.html
